apply from: gradle.ext.sharedModulesConstants
apply plugin: 'kotlin-android'
apply plugin: 'com.android.library'

android {
    // FIX: Default interface methods are only supported starting with Android N (--min-api 24)
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion project.properties.compileSdkVersion
    buildToolsVersion project.properties.buildToolsVersion
    testOptions.unitTests.includeAndroidResources = true

    defaultConfig {
        minSdkVersion project.properties.minSdkVersion
        targetSdkVersion project.properties.targetSdkVersion
        versionCode 10
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'

        // More info: http://myhexaville.com/2017/03/10/android-multidex/
        // Additionally, you should extend your application from MultiDexApplication
        multiDexEnabled = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        abortOnError true
        disable 'MissingTranslation'
        disable 'MissingQuantity'
    }

    // gradle 4.6 migration: disable dimensions mechanism
    // more: https://proandroiddev.com/advanced-android-flavors-part-4-a-new-version-fc2ad80c01bb
    flavorDimensions "default"

    productFlavors {
        stbeta {}
        ststable {}
        stfdroid {}
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:' + appCompatXVersion
    testImplementation 'junit:junit:' + junitVersion
    testImplementation 'org.robolectric:robolectric:' + robolectricVersion

    implementation project(':sharedutils')
    implementation project(':fragment-1.1.0')
    implementation project(':mediaserviceinterfaces')
    implementation project(':youtubeapi')
    implementation project(':filepicker-lib')

    implementation 'io.reactivex.rxjava2:rxandroid:' + rxAndroidVersion
    implementation 'io.reactivex.rxjava2:rxjava:' + rxJavaVersion

    //////// BEGIN EXOPLAYER /////////

    implementation project(':exoplayer-library')
    implementation project(':exoplayer-extension-okhttp')
    implementation project(':exoplayer-extension-cronet')

    // implementation 'com.amazon.android:exoplayer:' + amazonExoplayerVersion
    // implementation 'com.amazon.android:extension-okhttp:' + amazonExoplayerVersion

    // implementation 'com.google.android.exoplayer:exoplayer:' + exoplayerVersion
    // implementation 'com.google.android.exoplayer:extension-okhttp:' + exoplayerVersion

    // implementation 'com.github.amzn:exoplayer-amazon-port:' + amazonExoplayerJitpackVersion

    //////// END EXOPLAYER //////////

    //////// BEGIN MEDIA3 (new player stack, migration Track A) /////////
    // Added but not wired up yet (Phase M0): coexists with the exoplayer-amzn-2.10.6 fork above.
    // Runtime code will only instantiate these classes on API 23+ once the M1 PlayerController
    // interface/factory lands (androidx.media3 raised its own minSdk to 23 as of 1.9.0, see
    // <uses-sdk tools:overrideLibrary=.../> in smarttubetv/src/main/AndroidManifest.xml).
    // Verify latest stable release before shipping: https://developer.android.com/jetpack/androidx/releases/media3
    def media3Version = '1.10.1'
    implementation 'androidx.media3:media3-exoplayer:' + media3Version
    implementation 'androidx.media3:media3-exoplayer-dash:' + media3Version
    implementation 'androidx.media3:media3-exoplayer-hls:' + media3Version
    implementation 'androidx.media3:media3-ui:' + media3Version
    implementation 'androidx.media3:media3-datasource-okhttp:' + media3Version
    //////// END MEDIA3 //////////

    implementation 'androidx.media:media:' + mediaXVersion // exoplayer fix

    implementation 'com.github.bumptech.glide:glide:' + glideVersion

    implementation 'androidx.work:work-runtime:' + workVersion
    implementation 'com.google.guava:guava:' + guavaVersion // Work library deps

    implementation 'androidx.browser:browser:' + browserXVersion

    implementation 'androidx.core:core-ktx:' + kotlinCoreXVersion
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:' + kotlinVersion
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:' + kotlinxVersion

    implementation 'com.jakewharton:process-phoenix:' + phoenixVersion

    implementation project(':leanbackassistant')

    implementation project(':appupdatechecker2')

    implementation project(':slidableactivity') // https://github.com/r0adkll/Slidr
}
